# Generated by Django 4.2.8 on 2024-02-07 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleboard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='marker',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
