# Generated by Django 4.2.8 on 2024-02-07 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sampleboard_uuid_alter_marker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleboard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
