# Generated by Django 4.2.8 on 2024-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type_alter_marker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='hex_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
