# Generated by Django 4.2.8 on 2024-02-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
