# Generated by Django 4.2.8 on 2024-02-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type_alter_marker_type'),
        ('sticker_instructions', '0002_sticker_html_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='html_code',
        ),
        migrations.CreateModel(
            name='HTMLCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.TextField(blank=True, null=True)),
                ('sample_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sampleboard')),
            ],
        ),
    ]
