# Generated by Django 4.2.8 on 2024-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_instructions', '0004_alter_htmlcode_sample_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
