# Generated by Django 4.2.8 on 2024-02-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_type_alter_marker_type'),
        ('sticker_instructions', '0005_sticker_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionspdf',
            name='marker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marker'),
        ),
    ]
